name: Python package

on: [push]
env:
  POETRY_VERSION: 1.0


jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PYTHON_VERSION: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{matrix.PYTHON_VERSION}}
      uses: actions/setup-python@v1
      with:
        python-version: ${{matrix.PYTHON_VERSION}}
    - name: Install bwa
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: |
        wget https://github.com/lh3/bwa/releases/download/v0.7.17/bwa-0.7.17.tar.bz2
        tar -jxvf bwa-0.7.17.tar.bz2
        cd bwa-0.7.17
        make -j$(nproc)
        cd ..
        echo "::add-path::${GITHUB_WORKSPACE}/bwa-0.7.17/"
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry==${{env.POETRY_VERSION}}
    - name: Install cython
      run: |
        poetry run pip install cython==0.29.15
    - name: Install deps
      run: |
        poetry install --extras docs
    - name: Run pytest
      run: |
        poetry run python -m pytest --cov=samwell --cov-branch
    - name: Run lint
      run: |
        poetry run flake8 --config=flake8.cfg samwell
    - name: Run mypy
      run: |
        poetry run mypy -p samwell --config=mypy.ini
    - name: Run docs
      shell: bash
      run: |
        set -euo pipefail
        pushd docs
        poetry run make html
        popd
